coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 50%
        base: auto
        flags:
          - unit
flags:
  unit:
    carryforward: true
ignore:
  - "example"
